spring:
  application:
    name: logistica
  kafka:
    bootstrap-servers: 'http://localhost:29092'
    consumer:
      group-id: icompras-faturamento
      auto-offset-reset: earliest

icompras:
  config:
    kafka:
      topics:
        pedidos-faturados: 'icompras.pedidosFaturados'
        pedidos-enviados: 'icompras.pedidos-enviados'

server:
  port: 8084
